<div id="player"></div>
<h1>Escolha os sabores</h1>
<hr/>
<?php foreach ($this->flavors as $node): ?>
    <p>
        <h4>
            <?= $node['flavorName']->getProperty('name') ?>
            <a href="#" class="btn btn-warning btn-small">Adicionar</a>
        </h4>
        Ingredientes: 
        <?php foreach ($this->ingredients[$node['flavorName']->getId()] as $ingredient): ?>
            <?php if($ingredient->getProperty('link')): ?>
            <a href="#" class="link semantic_info" data-resource="<?= $ingredient->getProperty('link') ?>"
    	        data-original-title="<?= $ingredient->getProperty('name') ?>">
    	        <?= $ingredient->getProperty('name') ?></a>,
    	    <?php else: ?>
    	        <?= $ingredient->getProperty('name') ?>,
            <?php endif; ?>
        <?php endforeach; ?>
    <hr/>
    </p>
<?php endforeach; ?>



<!-- Modal -->
<div id="myModal" style="width: 300px;" class="modal hide fade"
	tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
	aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="modal-label"></h3>
	</div>
	<div class="modal-body">
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
		<!-- <button class="btn btn-primary">Save changes</button> -->
	</div>
</div>
