<?php /*foreach ($this->flavors as $node): ?>
    <p>
        <b><?= $node['flavorName']->getProperty('name') ?></b><br/>
        <?php foreach ($this->ingredients[$node['flavorName']->getId()] as $ingredient): ?>
            <?= $ingredient->getProperty('name'). ', ' ?>
        <?php endforeach; ?>
        
    </p>
<?php endforeach;*/
$sabores = array(
    array(
        'name' => 'Bacon',
        'ingredients' => array(
            array(
                'name' => 'Molho de tomate',
                'resource' => 'Tomato_sauce'
            ),
            array(
            		'name' => 'Mozarela',
            		'resource' => 'Mozzarella'
            ),
            array(
            		'name' => 'Bacon',
            		'resource' => 'Bacon'
            ),
            array(
            		'name' => 'Orégano',
            		'resource' => 'Oregano'
            ),
            array(
            		'name' => 'Azeitonas',
            		'resource' => 'Olive'
            ),
        )
    ),
    array(
		'name' => 'Bacon',
		'ingredients' => array(
			array(
					'name' => 'Molho de tomate',
					'resource' => 'Tomato_sauce'
			),
			array(
					'name' => 'Mozarela',
					'resource' => 'Mozzarella'
			),
			array(
					'name' => 'Manjericão',
					'resource' => 'Basil'
			),
			array(
					'name' => 'Azeitonas',
					'resource' => 'Olive'
			),
		)
    ),
);
?>
<h1>Sabores disponiveis</h1>
<p><a href="#" class="btn" rel="clickover-ajax" data-original-title="Notes" data-content="&lt;div class=&quot;progress progress-striped active&quot;&gt;&lt;div class=&quot;bar&quot; style=&quot;width: 100%;&quot;&gt;&lt;/div&gt;&lt;/div&gt;" data-contact-id="something">Clickover ajax example</a></p>
<hr>
<?php foreach ($sabores as $sabor): ?>
    <p>
    <h4>
    	<?= $sabor['name'] ?> <a class="btn btn-success btn-small" href="#">Adicionar</a>
    </h4>
    <?php foreach ($sabor['ingredients'] as $ingredient): ?>
        <a href="#" class="link semantic_info" data-resource="<?= $ingredient['resource'] ?>"
    	data-original-title="<?= $ingredient['name'] ?>"><?= $ingredient['name'] ?></a>,
    <?php endforeach; ?>
    </p>
    <hr>
<?php endforeach;?>



<!-- Modal -->
<div id="myModal" style="width: 300px;" class="modal hide fade"
	tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
	aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel">Bacon</h3>
	</div>
	<div class="modal-body">
		<p>
			CA - Cansalada | <a href="#" class="link">Ouvir</a>
		</p>
		<p>
			CS - Slanina | <a href="#" class="link">Ouvir</a>
		</p>
		<p>
			DE - Frühstücksspeck | <a href="#" class="link">Ouvir</a>
		</p>
		<p>
			EN - Bacon | <a href="#" class="link">Ouvir</a>
		</p>
		<p>
			ES - Panceta | <a href="#" class="link">Ouvir</a>
		</p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
		<!-- <button class="btn btn-primary">Save changes</button> -->
	</div>
</div>
<!-- Click over -->
<div id="semantic_content" style="display: none"></div>

