<h1>Escolha o produto</h1>
<hr>
<?php foreach ($this->products as $node): ?>
	<p>
	    <h4><?= $node['type']->getProperty('name') . ' ' . $node['size']->getProperty('name'); ?></h4>
	    <?php for($i=1; $i <= $node['relation']->getProperty('flavors');$i++):?>
    		<a href="<?= $this->url('flavors', array('action' => 'list', 'product' => $node['product']->getID(), 'pizzeria' => $this->pizzeria, 'flavors' => $i)) ?>">
    			<?= $i //TODO plural ?> Sabores
    		</a>
    		<?= ($i < $node['relation']->getProperty('flavors'))?' | ':'' ?> 
		<?php endfor; ?>
		<br/>
		R$: <?= number_format($node['relation']->getProperty('price'),2) ?><br/>
		<?= $node['relation']->getProperty('slices') ?> Pedaços<br/>
	</p>
	<hr>
<?php endforeach;?>