<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserControl\Module'                        => __DIR__ . '/Module.php',
    'UserControl\Controller\IndexController' => __DIR__ . '/src/UserControl/Controller/IndexController.php',
    'UserControlTest\Framework\TestCase'        => __DIR__ . '/tests/UserControl/Framework/TestCase.php',
    'UserControlTest\SampleTest'                => __DIR__ . '/tests/UserControl/SampleTest.php',
);
