<div class="hero-unit">
	<h1><?php echo sprintf($this->translate('Welcome to %sAkiPizza%s'), '<span class="zf-green">', '</span>') ?></h1>
	<p><?php echo sprintf($this->translate('Congratulations! You have successfully logged in to the AkiPizza portal. Here you can ask for a delicious pizza from your favorite pizzeria, view lots of information about flavors and its ingredients and much more. Have a lot of fun!')) ?></p>
    <p><a class="btn btn-success btn-large" href="<?php echo $this->url('pizzerias') ?>">
        <?php echo $this->translate('Ask for a pizza') ?>
    </a></p>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Manage your data') ?></h2>
        <p><?php echo sprintf($this->translate('Would you like to see your last requests, your delivery addresses, your favorite flavors and much more? Here you can!')) ?></p>
        <p><a class="btn btn-success" href="#"><?php echo $this->translate('See my data') //TODO write the right links?></a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Who are us?') ?></h2>
        <p><?php echo sprintf($this->translate('We are the Akipizza Team, and we are doing our best for you ask you delicious pizza faster with much more options and informations about it! ')) ?></p>
        <p><a class="btn btn-success" href="#"><?php echo $this->translate('Read more...') ?> </a></p>
   </div>
   <div class="span4">
        <h2><?php echo $this->translate('Contact us!') ?></h2>
        <p><?php echo sprintf($this->translate('Do you have doubts, suggestions or criticals? Please tell us, our team are ready to help you and your opinion is very importat to us!')) ?></p>
        <p><a class="btn btn-success" href="#"><?php echo $this->translate('Write a message') ?> </a></p>
   </div>
</div>
